# Required for KafkaProducer
general.kafka-topic=test-topic
general.kafka-bootstrapServers=localhost:9092
general.kafka-url=localhost:9092

# Spring default Kafka override
spring.kafka.bootstrap-servers=localhost:9092
